spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bo_gate
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    open-in-view: false
    generate-ddl: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /ui
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: classpath:logback.xml
  level:
    com.figo.weatherapp.feign: DEBUG
    org.springframework.web: ERROR
    org.hibernate: ERROR



